print("ADMISSION REPORT\n")
print("Admno."+"\t""Name"+"\t""Class"+"\t""Div.")
print("101"+"\t""Rajesh"+"\t""VIII"+"\t""B")
print("102"+"\t""Miya"+"\t""VII"+"\t""A")
print("103"+"\t""John"+"\t""VI"+"\t""B")
print("104"+"\t""Firoz"+"\t""VIII"+"\t""C")
print("105"+"\t""Sajan"+"\t""V"+"\t""D")

print()
print("ADMISSION REPORT\n")
print("Admno.\tName\tClass\tDiv.")
print("101\tRajesh\tVIII\tB")
print("102\tMiya\tVII\tA")
print("103\tJohn\tVI\tB")
print("104\tFiroz\tVIII\tC")
print("105\tSajan\tV\tD")

print()
print("ADMISSION REPORT\n")
print("Admno.", "Name", "Class", "Div.", sep='\t')
print(101, "Rajesh", "VIII", "B", sep="\t")
print(102, "Miya", "VII","A", sep="\t")
print(103, "John", "VI", "B", sep="\t")
print(104, "Firoz", "VIII", "C", sep="\t")
print(105, "Sajan", "V", "D", sep="\t")

print()
print("ADMISSION REPORT\n")
sp = '\t|\t'
print("Admno.", "Name", "Class", "Div.", sep=sp)
print(101, "Rajesh", "VIII", "B", sep=sp)
print(102, "Miya", "VII","A", sep=sp)
print(103, "John", "VI", "B", sep=sp)
print(104, "Firoz", "VIII", "C", sep=sp)
print(105, "Sajan", "V", "D", sep=sp)
